export const SET_PRODUCTS = "SET_PRODUCTS";
export const INCREMENT_PRODUCT_CART = "INCREMENT_PRODUCT_CART";
export const DECREMENT_PRODUCT_CART = "DECREMENT_PRODUCT_CART";
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART";